### PR TITLE
Changable cookie names and values

### PR DESCRIPTION
**Pull request by iamjochem**
hi again,

not the most handy PR (seeing as I made to functional tweak on top of a refactor of the code I did, namely: https://github.com/weare2ndfloor/cookieCuttr/pull/11).

the idea behind making the cookie name settable via an option is twofold:
- makes it easy to use acceptance cookies on different site sections and or subdomains 
- allows cookie acceptance to be forcibly reset (possibly desired/required as part of a policy change) even when someone has previously accepted cookies

... granted making the cookie value settable is a bit bogus but it might allow someone to save a few bytes :)

### CODE REVIEW

**Comment by cdwharton** [comment]
Hi there, looks like you've been busy! No I'm not doing any more development on this other than bugs & fixes.

**Comment by iamjochem** [comment]
@marcodejongh - I don't think it's a case of not appreciating, but rather that @weare2ndfloor has other priorities/interest/etc ... nothing wrong with laying a project to rest. (PS - ik zie geen 'extra features' op http://freshcotton.com - of ik begrijp niet waar je op doelt!)

I am interested to know how one would go about taking over a project (so that a fork becomes the canonical resource) - if @marcodejongh is interested in taking over development and @weare2ndfloor agrees - what would be the way forward?

**Comment by cdwharton** [comment]
@marcodejongh It's not that I don't appreciate your efforts, I think it is commendable for anyone to come and tidy up and improve people's code. @iamjochem is correct, we have laid this project to rest for a number of reasons. 1. The code is free from bugs and is being used by 100s of people 2. The code is integrated into a WordPress plugin and also a drupal plugin 3. The cookie consent law in the UK has taken a back seat now and many people aren't interested anymore. I'm not going to accept any pull request unless its a bug fix as I know the code is working and if I pull something, although it may be better coded, it means it all needs re-testing. I don't want to maintain 2 different sources of code across open source and WordPress/Drupal its just not an efficient use of my time.

I'm not going to pass development of CookieCuttr over to anyone. You are more than welcome to take CookieCuttr and rename it to something of your liking and I will link from the readme.md to your version for future improvements and development.

Just to reiterate, the open source and github community is amazing and I'm in awe of people who can refactor code into a fraction of what I can achieve. Thanks for your interest and your efforts thus far and I wish you good luck with wherever you decide to take your version of my cookie consent plugin.

**Comment by marcodejongh** [comment]
@weare2ndfloor you could have tagged the version you use in wordpress. Although I understand your point, It's a common problem of opening your source to the community.

I just merged all @iamjochem 's changes into my fork and I will rename it later today(when I figure out a equally fetching name ;) ) and put a link & credits to the original in the readme.md.

**Comment by cdwharton** [comment]
@marcodejongh How about CutACookie ? :)

**Comment by marcodejongh** [comment]
@weare2ndfloor that's a good one! I'll go with CuttACookie

**Comment by cdwharton** [comment]
@marcodejongh you know "Cutt" isn't a word, right? :p

**Comment by marcodejongh** [comment]
@weare2ndfloor i thought it would be cute as a extra reference to cookiecuttr

**Comment by cdwharton** [comment]
@marcodejongh Ah... you have to love the inside joke :) Nice thinking!

**Comment by iamjochem** [comment]
@weare2ndfloor niether is Cuttr ;-) ... I think it would be helpful to update CookieCuttr's README to clearly state that no more development is taking place in this repo (there is currently a "do a PR" message there :-)) .. it might also be worth sticking an aside in your cookiecuttr.com website stating the same thing (and possibly mentioning the fork) ... making it absolutely clear that people with feature/pull requests should go and bother @marcodejongh rather than @weare2ndfloor is probably beneficial to both of you :)

@marcodejongh - I recommend you enhance the README in your fork to contain info/examples related to options/usage so that your fork is nicely self contained - it will be confusing to rely on and/or refer to the documentation at cookiecuttr.com ... just a thought.

**Comment by cdwharton** [comment]
@iamjochem good point - I've updated readme, once new version is ready I'll update further :)

**Comment by marcodejongh** [comment]
@iamjochem I'll get to updating the readme.md later, I should probaply rename all the files(and function) aswell

**Pull request closed without merging**
