### PR TITLE
Tidying up documentation

### PR DESCRIPTION
**Pull request by philipcunningham**
I've moved most of the implementation detail into a nicely formatted markdown file.

I moved the details of the additional options to a [wiki page](https://github.com/unsymbol/cookieCuttr/wiki/Options) which seems like a sensible place for it.

### CODE REVIEW

**Comment by cdwharton** [comment]
Awesome work, thank you, I've been meaning to get around to doing a .md for ages, just not had time!

**Comment by philipcunningham** [comment]
:+1:

**Comment by philipcunningham** [comment]
Might be worth adding a wiki page with the options stuff at https://github.com/unsymbol/cookieCuttr/wiki/Options.

Also, nice plugin! :cat:

**Comment by cdwharton** [comment]
Cool, done and cheers :)

**Pull request merged**
